"""
Flipkart Product Scraper — Updated.

Flipkart uses dynamic class names (generated by CSS modules) that change
on each build. This scraper uses multiple strategies:
1. JSON-LD structured data (most reliable)
2. Product links + parent container parsing
3. Dynamic class detection with heuristics

Categories: sofas, beds, lighting, tables, decor, storage.
"""

import re
import json
import logging
from typing import Optional

from bs4 import BeautifulSoup

from scraper.base import get_session, get_headers, fetch_page, clean_price, clean_text, logger

# ──────────────────────────────────────────────
# Flipkart search URLs
# ──────────────────────────────────────────────
FLIPKART_SEARCHES = {
    "sofa": [
        "https://www.flipkart.com/search?q=sofa+set&otracker=search",
        "https://www.flipkart.com/search?q=3+seater+sofa&otracker=search",
        "https://www.flipkart.com/search?q=L+shape+sofa&otracker=search",
        "https://www.flipkart.com/search?q=recliner+sofa&otracker=search",
    ],
    "bed": [
        "https://www.flipkart.com/search?q=king+size+bed+with+storage&otracker=search",
        "https://www.flipkart.com/search?q=queen+size+bed&otracker=search",
        "https://www.flipkart.com/search?q=single+bed+wooden&otracker=search",
        "https://www.flipkart.com/search?q=bunk+bed&otracker=search",
    ],
    "lighting": [
        "https://www.flipkart.com/search?q=ceiling+light+modern&otracker=search",
        "https://www.flipkart.com/search?q=table+lamp+for+bedroom&otracker=search",
        "https://www.flipkart.com/search?q=floor+lamp+for+living+room&otracker=search",
        "https://www.flipkart.com/search?q=led+wall+lamp&otracker=search",
        "https://www.flipkart.com/search?q=pendant+light+for+dining&otracker=search",
    ],
    "table": [
        "https://www.flipkart.com/search?q=study+table+with+storage&otracker=search",
        "https://www.flipkart.com/search?q=coffee+table+center+table&otracker=search",
        "https://www.flipkart.com/search?q=dining+table+set+4+seater&otracker=search",
        "https://www.flipkart.com/search?q=office+desk+computer+table&otracker=search",
    ],
    "decor": [
        "https://www.flipkart.com/search?q=wall+mirror+decorative&otracker=search",
        "https://www.flipkart.com/search?q=wall+clock+for+living+room&otracker=search",
        "https://www.flipkart.com/search?q=flower+vase+ceramic&otracker=search",
        "https://www.flipkart.com/search?q=artificial+plant+for+home&otracker=search",
        "https://www.flipkart.com/search?q=curtains+for+living+room&otracker=search",
    ],
    "storage": [
        "https://www.flipkart.com/search?q=bookshelf+for+home&otracker=search",
        "https://www.flipkart.com/search?q=wardrobe+with+mirror&otracker=search",
        "https://www.flipkart.com/search?q=tv+unit+entertainment+unit&otracker=search",
        "https://www.flipkart.com/search?q=chest+of+drawers&otracker=search",
    ],
}


def _extract_from_json_ld(soup: BeautifulSoup, product_type: str) -> list[dict]:
    """Extract products from JSON-LD structured data in the page."""
    products = []

    for script in soup.find_all("script", type="application/ld+json"):
        try:
            data = json.loads(script.string or "")
        except (json.JSONDecodeError, TypeError):
            continue

        if not isinstance(data, dict) or data.get("@type") != "ItemList":
            continue

        for item in data.get("itemListElement", []):
            try:
                name = clean_text(item.get("name", ""))
                url = item.get("url", "")

                if not name or len(name) < 5 or not url:
                    continue

                # Flipkart JSON-LD doesn't always include price
                # We'll try to match with HTML later
                pid_match = re.search(r"pid=([A-Z0-9]+)", url)
                pid = f"FK_{pid_match.group(1)}" if pid_match else f"FK_{hash(name) % 100000:05d}"

                products.append({
                    "product_id": pid,
                    "product_name": name,
                    "url": url if url.startswith("http") else "https://www.flipkart.com" + url,
                    "product_type": product_type,
                })
            except Exception:
                continue

    return products


def _extract_from_product_links(soup: BeautifulSoup, product_type: str) -> list[dict]:
    """Extract products by finding product links and their parent containers."""
    products = []

    # Find all links to product pages
    product_links = soup.select("a[href*='/p/']")

    for link in product_links:
        try:
            href = link.get("href", "")
            url = href if href.startswith("http") else "https://www.flipkart.com" + href

            # Get the parent container (usually 2-3 levels up)
            container = link
            for _ in range(4):
                parent = container.find_parent(["div", "li", "article"])
                if parent:
                    container = parent
                else:
                    break

            # Try to find product name
            name = ""
            # Look for title attribute on the link itself
            title_attr = link.get("title", "")
            if title_attr and len(title_attr) > 5:
                name = clean_text(title_attr)

            # Or find text content in specific elements
            if not name:
                for sel in ["div[class]", "span[class]", "a[class]"]:
                    candidates = container.select(sel)
                    for c in candidates:
                        text = clean_text(c.get_text())
                        # Product names are typically 10-200 chars
                        if 10 < len(text) < 200 and "₹" not in text and "rating" not in text.lower():
                            name = text
                            break
                    if name:
                        break

            if not name or len(name) < 5:
                continue

            # Find price
            price = None
            price_texts = container.find_all(string=re.compile(r"₹"))
            for pt in price_texts:
                p = clean_price(pt)
                if p and p >= 100:
                    price = p
                    break

            if not price:
                # Try parent's text
                full_text = container.get_text()
                prices_found = re.findall(r"₹\s*([\d,]+)", full_text)
                for pf in prices_found:
                    try:
                        val = float(pf.replace(",", ""))
                        if val >= 100:
                            price = val
                            break
                    except ValueError:
                        continue

            if not price:
                continue

            # Image
            image_url = ""
            img = container.select_one("img[src*='rukminim'], img[src*='flipkart']")
            if not img:
                img = container.select_one("img")
            if img:
                image_url = img.get("src") or img.get("data-src") or ""

            # Product ID
            pid_match = re.search(r"pid=([A-Z0-9]+)", url)
            pid = f"FK_{pid_match.group(1)}" if pid_match else f"FK_{hash(name) % 100000:05d}"

            # Rating
            rating = ""
            rating_el = container.select_one("[class*='rating'], span[id*='productRating']")
            if not rating_el:
                # Look for stars pattern
                for span in container.find_all("span"):
                    text = span.get_text().strip()
                    if re.match(r"^\d\.?\d?$", text) and float(text) <= 5:
                        rating = text
                        break

            # Brand (sometimes separate, sometimes in name)
            brand = "Unknown"
            for span in container.find_all(["span", "div"]):
                text = clean_text(span.get_text())
                if text and 2 < len(text) < 30 and text != name and "₹" not in text:
                    # Check if it looks like a brand (short, capitalized)
                    if text[0].isupper() and " " not in text:
                        brand = text
                        break

            # Dimensions from name
            dimensions = ""
            dim_match = re.search(r"(\d+)\s*[xX×]\s*(\d+)(?:\s*[xX×]\s*(\d+))?", name)
            if dim_match:
                parts = [g for g in dim_match.groups() if g]
                dimensions = " x ".join(parts) + " cm"

            products.append({
                "product_id": pid,
                "product_name": name,
                "brand": brand,
                "price_value": price,
                "price_currency": "INR",
                "product_type": product_type,
                "image_url": image_url,
                "affiliate_url": url.split("&")[0],
                "source_url": url.split("&")[0],
                "dimensions": dimensions,
                "rating": rating,
                "source": "flipkart.com",
            })

        except Exception as e:
            logger.debug(f"Failed to parse Flipkart link: {e}")
            continue

    return products


def _parse_flipkart_results(html: str, product_type: str) -> list[dict]:
    """Parse Flipkart search results using multiple strategies."""
    soup = BeautifulSoup(html, "html.parser")

    # Strategy 1: Extract from product links (most reliable for Flipkart)
    products = _extract_from_product_links(soup, product_type)

    if products:
        # Deduplicate by product_id
        seen = set()
        unique = []
        for p in products:
            if p["product_id"] not in seen:
                seen.add(p["product_id"])
                unique.append(p)
        return unique

    # Strategy 2: JSON-LD (may not have prices)
    json_ld_products = _extract_from_json_ld(soup, product_type)
    if json_ld_products:
        # These won't have prices, but at least we get names and URLs
        for p in json_ld_products:
            p.setdefault("brand", "Unknown")
            p.setdefault("price_value", None)
            p.setdefault("price_currency", "INR")
            p.setdefault("image_url", "")
            p.setdefault("affiliate_url", p.get("url", ""))
            p.setdefault("source_url", p.get("url", ""))
            p.setdefault("dimensions", "")
            p.setdefault("source", "flipkart.com")
        return [p for p in json_ld_products if p.get("price_value")]

    return []


def scrape_flipkart(max_per_category: int = 100) -> list[dict]:
    """
    Scrape products from Flipkart with pagination.

    Args:
        max_per_category: Target products per search URL (paginated).

    Returns:
        List of product dicts.
    """
    logger.info("Starting Flipkart scraper (with pagination)...")
    session = get_session()
    all_products = []
    seen_ids = set()

    for product_type, urls in FLIPKART_SEARCHES.items():
        for base_url in urls:
            collected_for_url = 0
            max_pages = (max_per_category // 24) + 1  # ~24-40 per page

            for page in range(1, max_pages + 1):
                url = f"{base_url}&page={page}" if page > 1 else base_url
                logger.info(f"Scraping Flipkart [{product_type}] page {page}: {url[:80]}...")
                html = fetch_page(url, session=session, delay=2.5)
                if not html:
                    logger.warning(f"  → Failed to fetch page {page}")
                    break

                products = _parse_flipkart_results(html, product_type)

                if not products:
                    logger.info(f"  → No products on page {page}, stopping pagination")
                    break

                new_count = 0
                for p in products:
                    pid = p["product_id"]
                    if pid not in seen_ids:
                        seen_ids.add(pid)
                        all_products.append(p)
                        collected_for_url += 1
                        new_count += 1

                logger.info(f"  → Page {page}: {new_count} new products (url total: {collected_for_url}, grand total: {len(all_products)})")

                if collected_for_url >= max_per_category:
                    break

    logger.info(f"Flipkart scraping complete: {len(all_products)} products")
    return all_products
